fix: Update dependencies versions in package.json

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -2,7 +2,12 @@ pre-push:
   parallel: true
   commands:
     Latest and Greatest:
-      run: bunx taze major
+      run: |
+        output=$(bunx taze major)
+        if [[ "$output" != *"dependencies are already up-to-date"* ]]; then
+          echo "Error: Dependencies are not up-to-date"
+          exit 1
+        fi
 
 pre-commit:
   parallel: true
